### ISSUE TITLE
Could you provide MLLMs' parameters?

### ISSUE THREAD

**Issue by ShanWang-Shan** [junyangwang0410/AMBER#1]
Thank you for your great work. I am interested in using your dataset in my work. I successfully reproduced the results of LLaVA; however, I encountered difficulties in reproducing the results of InstructBlip and mPLUG-owl2. Could you kindly share the parameters you used, such as temperature, top_p, or any additional prompts? I would greatly appreciate it.

**Comment by junyangwang0410** [comment]
> Thank you for your great work. I am interested in using your dataset in my work. I successfully reproduced the results of LLaVA; however, I encountered difficulties in reproducing the results of InstructBlip and mPLUG-owl2. Could you kindly share the parameters you used, such as temperature, top_p, or any additional prompts? I would greatly appreciate it.

Thank you for your interest in our work. For all the models we evaluated in our paper, the generation parameters we used are consistent with the parameters provided by the official code. This means that you can directly use the official inference code without modifying any parameters. If the results cannot be reproduced, it may be due to model parameter updates, etc. Please refer to your latest results.
